# Generated by Django 4.2.8 on 2023-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
